#!/bin/bash
printf '\n'
printf '┌─────────────────────────────────────────────────────┐\n'
printf '│       CELESTIN PRUD'\''HOMME — ANTHROPIC APPLICATION   │\n'
printf '├─────────────────────────────────────────────────────┤\n'
printf '│  Staff Engineer · Skello (8 ans) · Paris            │\n'
printf '│  Applying for: Staff SWE, CI — Anthropic London     │\n'
printf '├─────────────────────────────────────────────────────┤\n'
printf '│  Ask me anything, or use a skill:                   │\n'
printf '│                                                     │\n'
printf '│  /celestin:cv            Full CV                    │\n'
printf '│  /celestin:cover-letter  Cover letter               │\n'
printf '│  /celestin:tech          Technical stack & CI/CD    │\n'
printf '│  /celestin:motivation    Why Anthropic              │\n'
printf '│  /celestin:fit           Role fit analysis          │\n'
printf '│  /celestin:ask [q]       Ask me directly            │\n'
printf '└─────────────────────────────────────────────────────┘\n'
printf '\n'
